const selector_to_name_mapping = {
  "label[for='work_parent_attributes_language_id']": "associations_parent_language",
  "label[for='work_moderated_commenting_enabled']": "privacy_comments_moderated",
  "#new_chapter > fieldset:nth-child(5) > dl > dt.notes": "nc_chapter_notes",
  "#new_chapter > fieldset:nth-child(7) > legend": "nc_chapter_post",
  "label[for='work_comment_permissions_disable_all']": "privacy_comments_permissions_disable_all",
  "dt.warning.required > label": "archive_warning",
  "label[for='work_wip_length']": "chaptered_wip_length",
  "p#parent-attributes-url-field-description": "associations_parent_url_note",
  "#new_chapter > fieldset.text > legend": "nc_chapter_text",
  "label[for='work_series_attributes_id']": "series_existing",
  "fieldset.preface > legend": "preface",
  "label[for='work_title']": "work_title",
  "label[for='work_archive_warning_strings_20']": "archive_warning_underage",
  "label[for='work_recipients_autocomplete']": "gift_this_work_to",
  "label[for='chapter_published_at']": "nc_chapter_published_at",
  "fieldset.work.meta > legend": "tags",
  "label[for='work_rating_string']": "rating",
  "option[value='Not Rated']": "rating_not_rated",
  "fieldset.work.meta > p.note": "tags_heading_note",
  "label[for='parent-options-show']": "associations_parent",
  "label[for='work_series_attributes_title']": "series_new",
  "label[for='end-notes-options-show']": "notes_end",
  "p.required.notice": "required",
  "label[for='work_language_id']": "language",
  "dd.skin > select#work_work_skin_id > option[value='229']": "skin_basic",
  "fieldset.work.text > legend": "work_text",
  "label[for='work_chapter_attributes_title']": "chaptered_wip_title",
  "option[value='Mature']": "rating_mature",
  "label[for='work_character_autocomplete']": "character",
  "label[for='front-notes-options-show']": "notes_beginning",
  "label[for='chapter_summary']": "nc_chapter_summary",
  "label[for='work_category_string_22']": "category_FM",
  "label[for='work_parent_attributes_author']": "associations_parent_author",
  "label[for='work_parent_attributes_translation']": "associations_parent_translation",
  "label[for='work_freeform_autocomplete']": "additional_tags",
  "option[value='Explicit']": "rating_explicit",
  "label[for='published_at']": "publication_date",
  "#new_chapter > fieldset:nth-child(5) > legend": "nc_chapter_preface",
  "fieldset.preface > dl > dt.notes": "notes",
  "label[for='work_category_string_24']": "category_Other",
  "label[for='chapter_position']": "nc_chapter_position",
  "dt.permissions.comments": "privacy_comments_permissions",
  "label[for='work_category_string_116']": "category_FF",
  "label[for='work_comment_permissions_enable_all']": "privacy_comments_permissions_all",
  "label[for='work_comment_permissions_disable_anon']": "privacy_comments_permissions_disable_anon",
  "label[for='work_category_string_21']": "category_Gen",
  "label[for='work_summary']": "summary",
  "option[value='General Audiences']": "rating_general",
  "label[for='co-authors-options-show']": "add_co_creators",
  "label[for='series-options-show']": "series",
  "dd.fandom.required > p.footnote": "fandom_footnote",
  "span.rtf-notes": "rich_text_notes",
  "label[for='work_work_skin_id']": "work_skin",
  "label[for='chapter_title']": "nc_chapter_title",
  "label[for='work_category_string_2246']": "category_Multi",
  "label[for='work_archive_warning_strings_18']": "archive_warning_death",
  "label[for='work_category_string_23']": "category_MM",
  "label[for='work_archive_warning_strings_17']": "archive_warning_graphic",
  "label[for='work_parent_attributes_title']": "associations_parent_title",
  "label[for='work_restricted']": "privacy_restriced",
  "label[for='work_fandom_autocomplete']": "fandom",
  "a.rtf-link": "rich_text",
  "label[for='work_archive_warning_strings_14']": "archive_warning_not_to_use",
  "fieldset.privacy > legend": "privacy",
  "label[for='backdate-options-show']": "backdate_options",
  "label[for='work_archive_warning_strings_19']": "archive_warning_rape",
  "label[for='chapter_wip_length']": "nc_chapter_of",
  "label[for='work_collection_names_autocomplete']": "post_to_collections_challenges",
  "label[for='work_relationship_autocomplete']": "relationship",
  "option[value='Teen And Up Audiences']": "rating_teen",
  "label[for='work_archive_warning_strings_16']": "archive_warning_no",
  "fieldset.create > legend": "post",
  "dd.skin > p.actions > a": "skin_public",
  "fieldset#associations > legend": "associations",
  "fieldset#chapter-ordering > legend": "nc_chapter_ordering",
  "dt.category > label": "category",
  "label[for='chapters-options-show']": "chaptered",
  "fieldset.create > ul > li:nth-child(1) > input": "preview_button",
  "fieldset.create > ul > li:nth-child(2) > input": "post_button",
  "fieldset.create > ul > li:nth-child(3) > input": "cancel_button",
  "fieldset:nth-child(7) > ul > li:nth-child(1) > input": "preview_button",
  "fieldset:nth-child(7) > ul > li:nth-child(2) > input": "post_button",
  "fieldset:nth-child(7) > ul > li:nth-child(3) > input": "cancel_button",
};
